[package]
name = "depthwise_color_consistency"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.16"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(cuda)'] }

[dependencies]
ndarray = "0.16.1"
