[package]
name = "py-depthwise_color_constancy"
version = "0.2.0"
edition = "2021"


[lib]
name = "depthwise_color_constancy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module"] }
depthwise_color_constancy = { workspace = true }
numpy = "0.24.0"
